Fix exit-node issue

diff --git a/luci-app-tailscaler/root/etc/init.d/tailscaler b/luci-app-tailscaler/root/etc/init.d/tailscaler
--- a/luci-app-tailscaler/root/etc/init.d/tailscaler
+++ b/luci-app-tailscaler/root/etc/init.d/tailscaler
@@ -3,7 +3,6 @@
 START=95
 USE_PROCD=1
 
-
 get_config() {
 	config_get_bool enabled $1 enabled 1
 	config_get_bool acceptRoutes $1 acceptRoutes 0
@@ -13,44 +12,64 @@ get_config() {
 	config_get hostname $1 hostname ""
 	config_get advertiseRoutes $1 advertiseRoutes ""
 }
-start_service() {
-	logger -t tailscaler 'start_service'
+
+apply_config() {
 	config_load tailscaler
 	config_foreach get_config settings
 	if [ "$enabled" != 1 ]; then
 		stop_service
-		return 1
+		return $?
 	fi
-	#
-	logger -t tailscaler 'start tailscale'
-	/etc/init.d/tailscale running || /etc/init.d/tailscale start
-	logger -t tailscaler 'start tailscaler'
-	# 
-	procd_open_instance
-	procd_set_param command /bin/sh /usr/libexec/tailscaler-up "$advertiseExitNode" --reset
+
+	logger -t tailscaler 'applying configuration'
+	/etc/init.d/tailscale running || /etc/init.d/tailscale start || {
+		logger -t tailscaler 'failed to start tailscale'
+		return 1
+	}
+
+	set -- --reset --timeout=15s
 	if [ -n "$loginServer" ]; then
-		procd_append_param command --login-server "$loginServer"
+		set -- "$@" --login-server "$loginServer"
 	fi
 	if [ -n "$authkey" ]; then
-		procd_append_param command --authkey "$authkey" 
+		set -- "$@" --auth-key "$authkey"
 	fi
 	if [ -n "$hostname" ]; then
-		procd_append_param command --hostname "$hostname" 
+		set -- "$@" --hostname "$hostname"
 	fi
 	if [ "$acceptRoutes" = 1 ]; then
-		procd_append_param command --accept-routes
+		set -- "$@" --accept-routes
 	fi
-	if [ -n "$advertiseRoutes" ];then
-		procd_append_param command --advertise-routes "$advertiseRoutes"
+	if [ -n "$advertiseRoutes" ]; then
+		set -- "$@" --advertise-routes "$advertiseRoutes"
 	fi
-	procd_append_param command --accept-dns false
+	set -- "$@" --accept-dns=false
 
-	procd_set_param stdout 1
-	procd_set_param stderr 1
-	procd_close_instance
-	logger -t tailscaler 'end tailscaler'
+	/bin/sh /usr/libexec/tailscaler-up "$advertiseExitNode" "$@"
 }
+
+start_service() {
+	apply_config
+}
+
+reload_service() {
+	apply_config
+}
+
 stop_service() {
-	/etc/init.d/tailscale stop
-	/etc/init.d/tailscale running && sleep 2
+	local exit_code=0
+
+	if /etc/init.d/tailscale running; then
+		/usr/sbin/tailscale set --advertise-exit-node=false || \
+			{
+				logger -t tailscaler 'failed to disable exit-node advertisement while stopping'
+				exit_code=1
+			}
+	fi
+	/etc/init.d/tailscale stop || exit_code=1
+	return "$exit_code"
+}
+
+service_triggers() {
+	procd_add_reload_trigger tailscaler
 }
diff --git a/luci-app-tailscaler/root/usr/libexec/tailscaler-up b/luci-app-tailscaler/root/usr/libexec/tailscaler-up
--- a/luci-app-tailscaler/root/usr/libexec/tailscaler-up
+++ b/luci-app-tailscaler/root/usr/libexec/tailscaler-up
@@ -1,15 +1,32 @@
 #!/bin/sh
 
 advertise_exit_node="$1"
+tailscale_bin="${TAILSCALE_BIN:-/usr/sbin/tailscale}"
 shift
 
-/usr/sbin/tailscale up "$@" || {
+case "$advertise_exit_node" in
+	0|1) ;;
+	*)
+		logger -t tailscaler "invalid advertiseExitNode value: $advertise_exit_node"
+		exit 2
+		;;
+esac
+
+"$tailscale_bin" up "$@" || {
 	logger -t tailscaler 'tailscale up failed; skipping exit-node configuration'
 	exit 1
 }
 
 if [ "$advertise_exit_node" = 1 ]; then
-	/usr/sbin/tailscale set --advertise-exit-node
+	"$tailscale_bin" set --advertise-exit-node || {
+		logger -t tailscaler 'failed to enable exit-node advertisement'
+		exit 1
+	}
+	logger -t tailscaler 'exit-node advertisement enabled'
 else
-	/usr/sbin/tailscale set --advertise-exit-node=false
+	"$tailscale_bin" set --advertise-exit-node=false || {
+		logger -t tailscaler 'failed to disable exit-node advertisement'
+		exit 1
+	}
+	logger -t tailscaler 'exit-node advertisement disabled'
 fi
